### ISSUE TITLE
Downloading snap to s3fs mount: Input/output error (os error 5)

### ISSUE THREAD

**Issue by coreylane** [awslabs/coldsnap#85] opened 2021-07-23 20:41 UTC
# Issue

Input/output error (os error 5) when downloading a snapshot directly to an [s3fs-fuse](https://github.com/s3fs-fuse/s3fs-fuse) mount

```
root@ip-172-31-36-184:~# coldsnap --region eu-central-1 --endpoint vpce-0026c3e27a1fcca8a-ldm2x3xi.ebs.eu-central-1.vpce.amazonaws.com download snap-079c86dd226586ca7 /s3-evidance/snap-079c86dd226586ca7.ebs
Failed to download snapshot: Failed to extend temporary file '/s3-evidance/.tmpsobmp0': Input/output error (os error 5)
```

# s3fs

```
root@ip-172-31-36-184:~# s3fs --version
Amazon Simple Storage Service File System V1.86 (commit:unknown) with GnuTLS(gcrypt)
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

## s3fs mount command 
```
s3fs evidance /s3-evidance -o iam_role="auto" -o url="https://s3-eu-central-1.amazonaws.com"
```

```
root@ip-172-31-36-184:~# grep s3 /etc/mtab
s3fs /s3-evidance fuse.s3fs rw,nosuid,nodev,relatime,user_id=0,group_id=0 0 0
```

## s3fs debug log
[coldsnap-github-issue-s3fs.log](https://gist.github.com/coreylane/39744f6ee2ec38ad037326999829d48b)

**Comment by bcressey** [comment] 2021-07-25 16:01
Can you try updating to the most recent release of s3fs?

1.87 has a bug fix that might address the issue here, since the error comes when we truncate the file to its expected size:
https://github.com/s3fs-fuse/s3fs-fuse/pull/1319

1.89 also fixes a regression writing objects larger than 10 GB, which is likely important for the snapshot use case.

**Comment by arnaldo2792** [comment] 2021-08-24 00:26
Hi @coreylane, are you are still experiencing this problem even after upgrading to the most recent releases of s3fs :+1: ?

**Comment by zmrow** [comment] 2022-01-21 16:38
I'll go ahead and close this for now - @coreylane if you continue to see this issue feel free to re-open! :)

**Closed as completed by zmrow** 2022-01-21 16:38 UTC
